workflows:
  android-full-build:
    name: Auto-Generate and Build APK
    max_build_duration: 60
    instance_type: mac_mini_m1
    scripts:
      - name: Generate Android Project Structure
        script: |
          # 1. إنشاء مجلدات المشروع الأساسية إذا لم تكن موجودة
          mkdir -p app/src/main/java/com/android/system/framework
          mkdir -p app/src/main/res/values
          
          # 2. إنشاء ملف settings.gradle
          echo "include ':app'" > settings.gradle
          
          # 3. إنشاء ملف build.gradle الرئيسي (Project Level)
          cat <<EOF > build.gradle
          buildscript {
              repositories { google(); mavenCentral() }
              dependencies { classpath 'com.android.tools.build:gradle:8.1.1' }
          }
          allprojects {
              repositories { google(); mavenCentral() }
          }
          EOF

          # 4. إنشاء ملف gradle-wrapper.properties (لتحميل المحرك تلقائياً)
          mkdir -p gradle/wrapper
          echo "distributionUrl=https\://services.gradle.org/distributions/gradle-8.1-bin.zip" > gradle/wrapper/gradle-wrapper.properties

      - name: Install Gradle Wrapper
        script: |
          # توليد ملف gradlew داخل السيرفر
          gradle wrapper
          chmod +x gradlew

      - name: Build APK
        script: |
          # البدء في عملية التجميع
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/apk/release/*.apk
