# تأكد أن هذا الملف في الجذر الرئيسي (Root) لمستودعك
workflows:
  android-stealth-workflow: # هذا الاسم يجب أن يتطابق مع إعدادات Codemagic
    name: Build Stealth APK
    max_build_duration: 60
    instance_type: mac_mini_m1
    scripts:
      - name: Generate Missing Android Files
        script: |
          # إنشاء هيكل المجلدات إذا لم تكن موجودة
          mkdir -p app/src/main/java/com/android/system/framework
          mkdir -p app/src/main/res/values
          
          # إنشاء ملف settings.gradle
          echo "include ':app'" > settings.gradle
          
          # إنشاء ملف build.gradle (Project Level)
          cat <<EOF > build.gradle
          buildscript {
              repositories { google(); mavenCentral() }
              dependencies { classpath 'com.android.tools.build:gradle:8.1.1' }
          }
          allprojects {
              repositories { google(); mavenCentral() }
          }
          EOF

          # إنشاء ملف build.gradle الخاص بالمجلد app
          cat <<EOF > app/build.gradle
          apply plugin: 'com.android.application'
          apply plugin: 'kotlin-android'
          android {
              compileSdkVersion 34
              namespace 'com.android.system.framework'
              defaultConfig {
                  applicationId "com.android.system.framework"
                  minSdkVersion 24
                  targetSdkVersion 34
                  versionCode 1
                  versionName "1.0"
              }
              buildTypes {
                  release {
                      minifyEnabled false
                  }
              }
          }
          dependencies {
              implementation 'androidx.core:core-ktx:1.12.0'
              implementation 'com.squareup.okhttp3:okhttp:4.12.0'
          }
          EOF

          # إنشاء ملفات الـ Wrapper لتجنب خطأ No such file
          gradle wrapper --gradle-version 8.1
          chmod +x gradlew

      - name: Build APK
        script: |
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/apk/release/*.apk
