workflows:
  android-stealth-workflow:
    name: Build Stealth APK
    max_build_duration: 60
    instance_type: mac_mini_m1
    scripts:
      - name: Generate Core Android Files
        script: |
          mkdir -p app/src/main/java/com/android/system/framework
          mkdir -p app/src/main/res/values
          echo "include ':app'" > settings.gradle
          echo "android.useAndroidX=true" > gradle.properties
          echo "android.enableJetifier=true" >> gradle.properties
          
          cat <<EOF > build.gradle
          buildscript {
              repositories { google(); mavenCentral() }
              dependencies { 
                  classpath 'com.android.tools.build:gradle:8.1.1'
                  classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.0'
              }
          }
          allprojects { repositories { google(); mavenCentral() } }
          EOF

          cat <<EOF > app/build.gradle
          plugins {
              id 'com.android.application'
              id 'kotlin-android'
          }
          android {
              namespace 'com.android.system.framework'
              compileSdk 34
              defaultConfig {
                  applicationId "com.android.system.framework"
                  minSdk 24
                  targetSdk 34
                  versionCode 1
                  versionName "1.0"
              }
              buildTypes {
                  release {
                      minifyEnabled false
                      // إضافة التوقيع التلقائي هنا
                      signingConfig signingConfigs.debug 
                  }
              }
              compileOptions {
                  sourceCompatibility JavaVersion.VERSION_17
                  targetCompatibility JavaVersion.VERSION_17
              }
              kotlinOptions { jvmTarget = '17' }
          }
          dependencies {
              implementation 'androidx.appcompat:appcompat:1.6.1'
              implementation 'androidx.core:core-ktx:1.12.0'
              implementation 'com.squareup.okhttp3:okhttp:4.12.0'
          }
          EOF

          cat <<EOF > app/src/main/res/values/styles.xml
          <resources>
              <style name="Theme.App" parent="Theme.AppCompat.NoActionBar" />
          </resources>
          EOF

          gradle wrapper --gradle-version 8.1.1
          chmod +x gradlew

      - name: Build and Sign APK
        script: |
          export JAVA_HOME=$JAVA_HOME_17
          # بناء نسخة موقعة بمفتاح التصحيح لكي تعمل على هاتفك
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/apk/release/*.apk
