workflows:
  android-stealth-workflow:
    name: Build Stealth APK
    max_build_duration: 60
    instance_type: mac_mini_m1
    scripts:
      - name: Generate Core Android Files
        script: |
          # 1. إنشاء المجلدات
          mkdir -p app/src/main/java/com/android/system/framework
          
          # 2. إنشاء ملف settings.gradle
          echo "include ':app'" > settings.gradle
          
          # 3. إنشاء ملف build.gradle الرئيسي (إصلاح مشكلة Kotlin Plugin)
          cat <<EOF > build.gradle
          buildscript {
              repositories { google(); mavenCentral() }
              dependencies { 
                  classpath 'com.android.tools.build:gradle:8.1.1'
                  classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.0'
              }
          }
          allprojects {
              repositories { google(); mavenCentral() }
          }
          EOF

          # 4. إنشاء ملف app/build.gradle (إصلاح مشكلة SDK و Plugins)
          cat <<EOF > app/build.gradle
          plugins {
              id 'com.android.application'
              id 'kotlin-android'
          }
          android {
              namespace 'com.android.system.framework'
              compileSdk 34
              defaultConfig {
                  applicationId "com.android.system.framework"
                  minSdk 24
                  targetSdk 34
                  versionCode 1
                  versionName "1.0"
              }
              buildTypes {
                  release {
                      minifyEnabled false
                  }
              }
          }
          dependencies {
              implementation 'androidx.core:core-ktx:1.12.0'
              implementation 'com.squareup.okhttp3:okhttp:4.12.0'
          }
          EOF

          # 5. توليد محرك Gradle ومنح الصلاحيات (حل مشكلة No such file)
          gradle wrapper --gradle-version 8.1.1
          chmod +x gradlew

      - name: Build APK
        script: |
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/apk/release/*.apk
