workflows:
  android-stealth-workflow:
    name: Build Stealth APK
    max_build_duration: 60
    instance_type: mac_mini_m1
    scripts:
      - name: Clean and Fix Permissions
        script: | 
          # البحث عن ملف gradlew في كل المجلدات ومنحه الصلاحية
          find . -name "gradlew" -exec chmod +x {} +
          
          # الدخول للمجلد الذي يحتوي على ملفات الأندرويد وتشغيل التنظيف
          # إذا كانت ملفاتك داخل مجلد اسمه app أو غيره، الكود التالي سيعالج ذلك
          GRADLEW_PATH=$(find . -name "gradlew" | head -n 1)
          if [ -z "$GRADLEW_PATH" ]; then
            echo "Error: gradlew not found in the repository!"
            exit 1
          fi
          
          cd $(dirname "$GRADLEW_PATH")
          ./gradlew clean
      - name: Build APK
        script: | 
          GRADLEW_PATH=$(find . -name "gradlew" | head -n 1)
          cd $(dirname "$GRADLEW_PATH")
          ./gradlew assembleRelease
    artifacts:
      - "**/build/outputs/apk/release/*.apk"
